### ISSUE TITLE
URL for application download

### ISSUE THREAD

**Issue by nxion** [jcscottiii/gdec#5]
> Get a better link for the VSCode.zip package

I wanted to discus this part in your TODO section. How did you come across this URL in the Dockerfile to download Visual Studio Code to begin with:

> https://az764295.vo.msecnd.net/public/0.10.1-release/VSCode-linux64.zip

I went looking around at how to download it from the Microsoft site. After looking at the soure code for the download page, I found this piece of JavaScript:

``` js
            var dv = getParameterByName('dv');
            if (dv) {
                $('#confirmation').show();
                reportAction('Download', dv, { 'version': 'preview' });

                var links = {
                    'osx': 'http://go.microsoft.com/fwlink/?LinkID=620882',
                    'win': 'http://go.microsoft.com/fwlink/?LinkID=623230',
                    'linux64': 'http://go.microsoft.com/fwlink/?LinkID=620884',
                    'linux32': 'http://go.microsoft.com/fwlink/?LinkID=620885',
                    'winzip': 'http://go.microsoft.com/fwlink/?LinkID=623231'
                }
                window.location.href = links[dv];
            }
        });
```

The most interesting piece of this snippet is the `var links`. If you use browse to one of the links above it will trigger a download for the appropriate platform. Maybe it can be used to replace the one you have?

**Comment by jcscottiii** [comment]
I originally got it from this: http://www.cyberciti.biz/faq/debian-ubuntu-fedora-linux-installing-visual-studio-code/

They just recently put these up: https://github.com/Microsoft/vscode/wiki/Previous-Releases

All those links look similar so we might be good.

**Comment by nxion** [comment]
Maybe we can add a separate script to check to see what the latest version is and then download it instead of it being hard coded?

**Comment by jcscottiii** [comment]
We should keep the version pinned / add more version pinning to more packages. This reduces [`unanticipated failures`](https://docs.docker.com/engine/articles/dockerfile_best-practices/)

**Comment by jcscottiii** [comment]
Also, I'm working on #6 where I started pinning the versions

**Comment by jcscottiii** [comment]
Another way of finding the true link, after you click the link to download the binary, if you are using Chrome, go to Downloads and you'll see the real link:
![image](https://cloud.githubusercontent.com/assets/7788930/11589238/ee1be620-9a54-11e5-805d-315ebbd81d67.png)

**Comment by nxion** [comment]
Wow, can't believe I never noticed that before.

> Also, I'm working on #6 where I started pinning the versions

I missed that comment. My mistake. I will close this issue.
